import pandas as pd


def generate_ai_charts(df):

    charts = []


    # Category Analysis

    if "Category" in df.columns:

        category_sales = (
            df.groupby("Category")
            ["Sales"]
            .sum()
            .reset_index()
        )


        charts.append({

            "title":"Sales by Category",

            "type":"bar",

            "data":
            category_sales.to_dict(
                orient="records"
            ),

            "x":"Category",

            "y":"Sales",


            "explanation":
            "This chart compares revenue generated by each category.",


            "insight":
            f"{category_sales.loc[category_sales['Sales'].idxmax(),'Category']} is generating the highest sales.",


            "recommendation":
            "Focus business strategy on high performing categories."

        })



    # Product Analysis

    if "Product Name" in df.columns and "Sales" in df.columns:


        product_sales = (
            df.groupby("Product Name")
            ["Sales"]
            .sum()
            .sort_values(
                ascending=False
            )
            .head(10)
            .reset_index()
        )



        charts.append({

            "title":"Top Products by Sales",

            "type":"bar",

            "data":
            product_sales.to_dict(
                orient="records"
            ),


            "x":"Product Name",

            "y":"Sales",


            "explanation":
            "Shows products contributing most revenue.",


            "insight":
            f"{product_sales.iloc[0]['Product Name']} is the best selling product.",


            "recommendation":
            "Increase inventory and promotion for top products."

        })


    return charts